### ISSUE TITLE
clone from original and run in pythonista3.4

### ISSUE THREAD

**Issue by icicleforest** [icicleforest/gittle#1]

**Comment by icicleforest** [comment]
stash: <class 'TypeError'>: object of type 'map' has no len()
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/stash/system/shruntime.py", line 546, in exec_py_file
    exec (code, namespace, namespace)
  File "../../bin/git.py", line 702, in <module>
    ns.func(args)
  File "../../bin/git.py", line 187, in git_status
    repo = _get_repo()
  File "../../bin/git.py", line 113, in _get_repo
    return Gittle(repo_dir)
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/gittle/gittle.py", line 134, in __init__
    self.hidden_regexes.extend(self._get_ignore_regexes())
  File "/var/containers/Bundle/Application/6650134D-64A4-49E1-A313-87EDCA139204/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/fnmatch.py", line 90, in translate
    i, n = 0, len(pat)
TypeError: object of type 'map' has no len()

**Comment by icicleforest** [comment]
stash: <class 'NameError'>: name 'basestring' is not defined
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/stash/system/shruntime.py", line 546, in exec_py_file
    exec (code, namespace, namespace)
  File "../../bin/git.py", line 702, in <module>
    ns.func(args)
  File "../../bin/git.py", line 613, in git_diff
    porcelain.diff_tree('.', repo[repo['HEAD'].tree].id, repo[index_sha].id, sys.stdout)
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/gittle/gittle.py", line 1222, in __getitem__
    sha = self._parse_reference(key)
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/gittle/gittle.py", line 822, in _parse_reference
    return self._commit_sha(ref_string)
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/gittle/gittle.py", line 777, in _commit_sha
    if utils.git.is_sha(commit_obj):
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/gittle/utils/git.py", line 212, in is_sha
    return isinstance(sha, basestring) and len(sha) == 40
NameError: name 'basestring' is not defined

**Comment by icicleforest** [comment]
stash: <class 'TypeError'>: 'name' must be bytestring, not str
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/stash/system/shruntime.py", line 546, in exec_py_file
    exec (code, namespace, namespace)
  File "../../bin/git.py", line 702, in <module>
    ns.func(args)
  File "../../bin/git.py", line 613, in git_diff
    porcelain.diff_tree('.', repo[repo['HEAD'].tree].id, repo[index_sha].id, sys.stdout)
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/gittle/gittle.py", line 1222, in __getitem__
    sha = self._parse_reference(key)
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/gittle/gittle.py", line 822, in _parse_reference
    return self._commit_sha(ref_string)
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/gittle/gittle.py", line 781, in _commit_sha
    commit_obj = self.repo[commit_obj]
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/dulwich/repo.py", line 827, in __getitem__
    raise TypeError(f"'name' must be bytestring, not {type(name).__name__:.80}")
TypeError: 'name' must be bytestring, not str

**Comment by icicleforest** [comment]
stash: <class 'TypeError'>: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/stash/system/shruntime.py", line 546, in exec_py_file
    exec (code, namespace, namespace)
  File "../../bin/git.py", line 702, in <module>
    ns.func(args)
  File "../../bin/git.py", line 613, in git_diff
    porcelain.diff_tree('.', repo[repo['HEAD'].tree].id, repo[index_sha].id, sys.stdout)
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/gittle/gittle.py", line 1226, in __getitem__
    sha = self._parse_reference(key)
  File "/private/var/mobile/Containers/Shared/AppGroup/D69C52C3-0192-48C6-8487-E3235BCF6A63/Pythonista3/Documents/site-packages/gittle/gittle.py", line 821, in _parse_reference
    if '~' in ref_string:
TypeError: a bytes-like object is required, not 'str'

**Comment by icicleforest** [comment]
```
$ git status
fatal: invalid refspec ':+refs/heads/*:refs/remotes/origin/*'

$ diff config .git/config
12c12
<       fetch = +refs/heads/*:refs/remotes/origin/*
---
>       fetch = :+refs/heads/*:refs/remotes/origin/*
```
